# Generated by Django 5.1.2 on 2024-10-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecthub', '0005_contributor_created_time_alter_issue_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='user',
            new_name='author',
        ),
    ]
