# Generated by Django 5.1.2 on 2024-10-16 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecthub', '0006_rename_user_contributor_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('author', 'project')},
        ),
    ]
