# Generated by Django 5.1.2 on 2024-10-16 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecthub', '0007_alter_contributor_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributor',
            new_name='Contribute',
        ),
    ]
